apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: webapps-tls
  namespace: flux-system
spec:
  interval: 5m
  path: ./environments/webapps/tls
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
