apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webapps

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../platform/vault/tls-base
  - vault-vars.yaml

configMapGenerator:
  - name: vault-vars
    behavior: merge
    literals:
      - VAULT_SECRET_PATH=certs/nginx
      - VAULT_ROLE=nginx-role
      - ROLLOUT_TRIGGER=tls-v1

patches:
  - path: patch-vault-vars.yaml
