apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-tls-app
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-template-tls.crt: |
          {{- with secret "{{ .Values.VAULT_SECRET_PATH }}" -}}
          {{ .Data.data.tls.crt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-tls.key: |
          {{- with secret "{{ .Values.VAULT_SECRET_PATH }}" -}}
          {{ .Data.data.tls.key }}
          {{- end }}
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{- with secret "{{ .Values.VAULT_SECRET_PATH }}" -}}
          {{ .Data.data.ca.crt }}
          {{- end }}
        vault.hashicorp.com/role: "{{ .Values.VAULT_ROLE }}"
        rollout-trigger: "{{ .Values.ROLLOUT_TRIGGER }}"