apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-tls-app
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-tls-app
  template:
    metadata:
      labels:
        app: vault-tls-app
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80